#!/usr/bin/env bash

# Open a man page as a PDF in Preview.app
pman () {
    man -t $@ | open -f -a /Applications/Preview.app
}


# If the man page is just a reference to "Bash built-in commands" man page, use `help` instead
man_or_help() {
    if [[ $# -lt 1 ]] || [[ -z $1 ]]; then
        printf 'What manual page or help topic do you want?\n' >&2
        return 1
    fi

    # Get the filename of the manfile
    local manfile="$(command man -w "$@" 2>&-)"
    if [[ $? != 0 ]] || [[ -z $manfile ]]; then
        printf 'No manual or help entry for %s\n' "$*"
        return 2
    fi

    # If the command is a Bash builtin, display `help` instead of a HTML manpage
    if [[ "$(basename "$manfile")" == 'builtin.1' ]]; then
        command help "$@"
    else
        command man "$@"
    fi
}
#alias man="man_or_help"


# Takes a search regex, and prints all the processes with open files whose path matches the regex
using() {
    local search_path='/Volumes'
    [[ $# -gt 0 ]] && search_path="$@"
    sudo lsof | awk -v path="$search_path" '{if($9 ~ path) print;}'
}

# vim: set tabstop=4 shiftwidth=4 textwidth=100 expandtab foldmethod=manual filetype=sh:
