#!/usr/bin/env bash

for path in "$@"; do
# ignore any arguments
if [[ "$path" = -* ]]; then :
else
  dst=${path##*/}
  # append the time if necessary
  while [ -e ~/.Trash/"$dst" ]; do
    dst="$dst "$(date +%H-%M-%S)
  done
  mv "$path" ~/.Trash/"$dst"
fi
done
