#!/usr/bin/env bash

# Use '{}' as a placeholder for arguments to xargs
alias xargs='xargs -0 -I{}'

# Shorter alias to grep a fixed string; case insensitive; ignore binary files.
alias fgrep='grep -Fi'

# Run 'less' but disable line wrapping (and enable horizontal scrolling)
alias lesw='less -S'

# Fat fingers
alias sudp='sudo'
alias la='ls'

# Shortcut to cd to my current homesick castle directory
type -t homesick >/dev/null && alias castle='cd $(homesick show_path)'

if type -t tmux >/dev/null; then
	# Create a new tmux session with a given name
	alias tnew='tmux new -s'
	# Connct to an existing tmux session with a given name
	alias topen='tmux a -t'
fi


# Show public IP address
alias whatismyip="curl -s 'http://ipecho.net/plain' && echo"


# Source our OS-specific aliases
[[ "$OS" == "Mac" ]] && . ~/.config/bash/shell_aliases.mac
[[ "$OS" == "Linux" ]] && . ~/.config/bash/shell_aliases.linux
