#!/usr/bin/env bash

# Use '{}' as a placeholder for arguments to xargs
alias xargs='xargs -0 -I{}'

# Alias `grep` to automatically enable color output
alias grep='grep --color=auto'
# Shorter alias to grep a fixed string; case insensitive; ignore binary files.
alias fgrep='grep --color=auto -Fi'

# Run 'less' but disable line wrapping (and enable horizontal scrolling)
alias lesw='less -S'

# Fat fingers
alias sudp='sudo'
alias la='ls'

# Shortcut to cd to my current homesick castle directory
type -t homesick >/dev/null && alias castle='cd $(homesick show_path)'

# `tm` will open (and create, if necessary) a tmux session named for the current user
type -t tmux 2>&1 >/dev/null && alias tm="tmux new-session -A -s \"$USER\""

# Show public IP address
alias whatismyip="curl -s 'http://ipecho.net/plain' && echo"

# Allow aliases to work with `sudo`
alias sudo='sudo '

alias g='git'

# Command to load the latest history from all terminals into this terminal's history buffer
alias histup='history -a && history -c && history -r'

# Sane defaults to rsync: archive mode (equals -rlptgoD; no -H,-A,-X), skip files that are newer on
# the destination (update mode), verbose, recurse, preserve timestamp, preserve +x flag, compress
# transfer, use ~/.rsync_eclude.conf to set excluded files
alias mrsync="rsync -auvrtEz --exclude-from=$HOME/.rsync_exclude.conf --progress --rsh=ssh"

# `bashrc`: Open up all our Bash configuration files at once in our editor
# $VISUAL is set to 'mvim -f' in OS X by default, but we don't want the '-f' here (it tells MacVim
# to not fork, and the command will not return until MacVim is closed.)
alias bashrc="command find ~/.config/bash -not -name 'shell_history' -not -type d -print0 | command xargs -0 -J % $( ([[ "$VISUAL" == 'mvim -f' ]] && printf 'mvim') || printf '%s' "$VISUAL") ~/.bash_profile ~/.inputrc ~/.ssh/config % ~/.bashrc ~/.bash_logout"

# Source our OS-specific aliases
[[ "$OS" == "Mac" ]] && . ~/.config/bash/shell_aliases.mac
[[ "$OS" == "Linux" ]] && . ~/.config/bash/shell_aliases.linux
