#!/usr/bin/env bash

# This file defines new Bash commands that are too complicated to be aliases, but too simple to get
# their own script file in ~/bin. These commands are defined as functions, and this file is sourced
# in ~/.bash_profile so that these functions are available globally in Bash.


# Make a directory and immediately cd to it
mkcd() {
    mkdir -p -v "$@" && cd "$@"
}


# Runs `ssh` as normal, but first sets the terminal title to be the name of the remote server
ssh_and_set_title() {
    local original_args="$*"
    local arg=''
    OPTIND=1

    while getopts ':1246AaCfgKkMNnqsTtVvXxYyb:c:D:e:F:I:i:L:l:m:O:o:p:R:S:W:w:' arg; do
        case $arg in
            \?|:)
                ssh ${original_args[*]}
                return $?;;
            *)
                :;;
        esac
    done
    shift $((OPTIND-1))

    local server_name="${1##*@}"
    printf '\e]1;SSH: %s\007' "$server_name" && ssh ${original_args[*]}
    return $?
}
alias ssh=ssh_and_set_title


# Search for files in <path> (defaults to '.') whose filename includes <name>
# Usage: findfiles <name> [<path>]
findfiles() {
    if [[ $# -gt 1 ]]; then
        local search_path=$2
    else
        local search_path='.'
    fi
    find $search_path -iname "*$1*"
}


# Make a tmp directory, switch to it and copy its name to the system's paste buffer
delme () {
    local TMPDIR="$(mktemp -d -t delme)"
    cd "$TMPDIR"
    [[ "$OS" == "Mac" ]] && pwd | tr -d "\n" | pbcopy
}



# Check the spelling of a word with aspell (if installed)
if type -t aspell>/dev/null; then
	spell() {
		echo "$@" | aspell pipe | grep -v 'but really Aspell'
	}
fi


# Grep for a process name and show the results
psgrep() {
	search_term="$*"
	procs="$(command ps -Aww -o pid,user,command)"
	echo "$procs" | head -n 1
	echo "$procs" | grep -i "[${search_term:0:1}]${search_term:1}"
}




if [[ "$OS" == "Mac" ]] && [[ -f ~/.config/bash/shell_commands.mac ]]; then
    source ~/.config/bash/shell_commands.mac
fi
