"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
pull = ["util", "exec", "--", "bash", "-c", """
jj git fetch && jj rebase -s 'last_pull+ ~ ::trunk() ~ immutable()' -d 'trunk()' && jj bookmark move --from last_pull --to 'trunk()'
"""]
