#!/usr/bin/env bash

if head -n 1 "$1" | grep -E '^.{51,}'; then
	echo "Error: Summary too long (must be <= 50 characters)" >&2
	exit 1
fi

MSG="$(cat "$1")"
echo "$MSG" | expand | fold -s -w 72 > "$1"
exit 0
